---
name: Updates auto merge

on:
  workflow_run:
      workflows:
          - Repo tests
          - Auto-commit updates
      types:
          - completed
      branches:
          - auto-updates

jobs:
  automerge:
    if: github.event.review.state == 'approved' || !github.event.review
    runs-on: ubuntu-latest
    steps:
      - uses: reitermarkus/automerge@v1
        with:
          token: ${{ secrets.GHTOKEN }}
          merge-method: rebase
          do-not-merge-labels: never-merge
          # required-labels: automerge
          pull-request: ${{ github.event.inputs.pull-request }}
          dry-run: true